apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
  namespace: url-shorter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          imagePullPolicy: Always
          image: ghcr.io/dominik48n/query:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_HOST
              value: postgres.example.com:5432
            - name: POSTGRES_USERNAME
              value: urls_ro
            - name: POSTGRES_PASSWORD
              value: topsecret
            - name: POSTGRES_DATABASE
              value: urls
            - name: REDIS_HOSTS
              value: redis01.example.com:6379,redis02.example.com:6379,redis03.example.com:6379
            - name: REDIS_PASSWORD
              value: topsecret
            - name: URL_CACHING_TIME
              value: "180"
            - name: FALLBACK_URL
              value: https://example.com
            - name: HTTP_PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: query
  namespace: url-shorter
spec:
  selector:
    app: query
  ports:
    - port: 3000
      targetPort: 80
  type: LoadBalancer
