apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
  namespace: url-shorter
spec:
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          imagePullPolicy: Always
          image: ghcr.io/dominik48n/query:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: query
  namespace: url-shorter
spec:
  selector:
    app: query
  ports:
    - port: 3000
      targetPort: 80
