apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: url-shorter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          imagePullPolicy: Always
          image: ghcr.io/dominik48n/url-users:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_HOST
              value: postgres.example.com:5432
            - name: POSTGRES_USERNAME
              value: users
            - name: POSTGRES_PASSWORD
              value: topsecret
            - name: POSTGRES_DATABASE
              value: users
            - name: HTTP_PORT
              value: "3000"
            - name: SESSION_TIME
              value: "60"
            - name: JWT_SECRET
              value: abc
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: url-shorter
spec:
  selector:
    app: users
  ports:
    - port: 3000
      targetPort: 80
  type: LoadBalancer
